# dynasty_game.py
# =========================================
# KBO Dynasty - 경기 시뮬레이션 엔진 (일괄 처리 버전)
# 주당 DB 호출: 조회 3회 + upsert 2회 = 5회
# 시즌 전체 일괄(simulate_rest_of_season): 조회 3회 + upsert 3~4회
# 사전 준비:
#   ALTER TABLE dynasty_schedule ALTER COLUMN id SET GENERATED BY DEFAULT;
#   ALTER TABLE dynasty_team ALTER COLUMN id SET GENERATED BY DEFAULT;
# =========================================

import random
from dynasty_utils import get_supabase


# =========================================
# 한 주 경기 전체 시뮬레이션
# =========================================
def simulate_week(save_id, season, week):
    sb = get_supabase()

    games = (
        sb.table("dynasty_schedule")
        .select("*")
        .eq("save_id", save_id)
        .eq("season", season)
        .eq("week", week)
        .eq("played", False)
        .execute()
        .data
    )

    if not games:
        return

    teams, powers = _load_teams_and_powers(sb, save_id)
    team_map = {t["id"]: t for t in teams}

    game_upserts = []

    for g in games:
        home_id = g["home_team"]
        away_id = g["away_team"]

        home_score, away_score = _simulate_game(
            powers.get(home_id, {"bat": 50.0, "pit": 50.0}),
            powers.get(away_id, {"bat": 50.0, "pit": 50.0}),
        )

        game_upserts.append(
            {
                "id": g["id"],
                "save_id": save_id,
                "season": season,
                "week": week,
                "home_team": home_id,
                "away_team": away_id,
                "home_score": home_score,
                "away_score": away_score,
                "played": True,
            }
        )

        _apply_result(team_map[home_id], team_map[away_id], home_score, away_score)

    sb.table("dynasty_schedule").upsert(game_upserts).execute()
    _upsert_teams(sb, teams)


# =========================================
# 남은 시즌 전체 일괄 시뮬레이션 (sim_all용)
# 모든 주차를 메모리에서 처리 후 한번에 반영
# =========================================
def simulate_rest_of_season(save_id, season, from_week):
    sb = get_supabase()

    games = (
        sb.table("dynasty_schedule")
        .select("*")
        .eq("save_id", save_id)
        .eq("season", season)
        .gte("week", from_week)
        .eq("played", False)
        .execute()
        .data
    )

    if not games:
        return

    teams, powers = _load_teams_and_powers(sb, save_id)
    team_map = {t["id"]: t for t in teams}

    game_upserts = []

    games.sort(key=lambda g: g["week"])

    for g in games:
        home_id = g["home_team"]
        away_id = g["away_team"]

        home_score, away_score = _simulate_game(
            powers.get(home_id, {"bat": 50.0, "pit": 50.0}),
            powers.get(away_id, {"bat": 50.0, "pit": 50.0}),
        )

        game_upserts.append(
            {
                "id": g["id"],
                "save_id": save_id,
                "season": season,
                "week": g["week"],
                "home_team": home_id,
                "away_team": away_id,
                "home_score": home_score,
                "away_score": away_score,
                "played": True,
            }
        )

        _apply_result(team_map[home_id], team_map[away_id], home_score, away_score)

    for i in range(0, len(game_upserts), 100):
        sb.table("dynasty_schedule").upsert(game_upserts[i : i + 100]).execute()

    _upsert_teams(sb, teams)


# =========================================
# 승패 반영 (메모리)
# =========================================
def _apply_result(home, away, home_score, away_score):
    if home_score > away_score:
        home["wins"] += 1
        away["losses"] += 1
    elif away_score > home_score:
        away["wins"] += 1
        home["losses"] += 1
    else:
        home["ties"] += 1
        away["ties"] += 1


# =========================================
# 팀 성적 일괄 upsert
# =========================================
def _upsert_teams(sb, teams):
    rows = []
    for t in teams:
        rows.append(
            {
                "id": t["id"],
                "save_id": t["save_id"],
                "team_name": t["team_name"],
                "logo": t["logo"],
                "color": t["color"],
                "stadium": t["stadium"],
                "is_user": t["is_user"],
                "wins": t["wins"],
                "losses": t["losses"],
                "ties": t["ties"],
            }
        )
    sb.table("dynasty_team").upsert(rows).execute()


# =========================================
# 전체 팀 + 전력 로드 (조회 2회)
# 로스터 전체를 1번에 가져와 팀별로 분배
# =========================================
def _load_teams_and_powers(sb, save_id):
    teams = (
        sb.table("dynasty_team")
        .select("*")
        .eq("save_id", save_id)
        .execute()
        .data
    )

    roster = (
        sb.table("dynasty_roster")
        .select("team_id, role, depth, dynasty_player(overall, positions)")
        .eq("save_id", save_id)
        .execute()
        .data
    )

    by_team = {}
    for r in roster:
        by_team.setdefault(r["team_id"], []).append(r)

    powers = {}
    for t in teams:
        powers[t["id"]] = _calc_power(by_team.get(t["id"], []))

    try:
        from dynasty_staff import get_staff_effects
        effects = get_staff_effects(save_id)
        for tid, e in effects.items():
            if tid in powers:
                powers[tid]["bat"] *= (1 + e["sim"])
                powers[tid]["pit"] *= (1 + e["sim"])
    except Exception as ex:
        print(f"[dynasty_game] 스태프 효과 skip: {ex}")

    try:
        from dynasty_facility import get_facility_effects
        fac = get_facility_effects(save_id)
        for tid in powers:
            powers[tid]["home_adv"] = fac.get(tid, {}).get("home_adv", 0.0)
    except Exception as ex:
        print(f"[dynasty_game] 시설 효과 skip: {ex}")

    return teams, powers


# =========================================
# 팀 전력 계산 (메모리)
# =========================================
def _calc_power(roster):
    if not roster:
        return {"bat": 50.0, "pit": 50.0}

    batters = []
    pitchers = []

    for r in roster:
        p = r["dynasty_player"]
        if p is None:
            continue
        role = r["role"]
        if role in ("SP", "RP", "CP"):
            pitchers.append((role, r["depth"], p["overall"]))
        elif role == "START":
            batters.append((r["depth"], p["overall"]))

    if not batters:
        all_bat = [
            (r["depth"], r["dynasty_player"]["overall"])
            for r in roster
            if r["dynasty_player"]
            and "P" not in (r["dynasty_player"]["positions"] or "")
        ]
        all_bat.sort(key=lambda x: -x[1])
        batters = all_bat[:9]

    if not pitchers:
        all_pit = [
            ("SP", r["depth"], r["dynasty_player"]["overall"])
            for r in roster
            if r["dynasty_player"]
            and "P" in (r["dynasty_player"]["positions"] or "")
        ]
        all_pit.sort(key=lambda x: -x[2])
        pitchers = all_pit[:8]

    bat_power = (
        sum(o for _, o in batters) / len(batters) if batters else 50.0
    )

    sp = [o for role, _, o in pitchers if role == "SP"]
    bp = [o for role, _, o in pitchers if role in ("RP", "CP")]

    sp_avg = sum(sp) / len(sp) if sp else 50.0
    bp_avg = sum(bp) / len(bp) if bp else 50.0

    pit_power = sp_avg * 0.6 + bp_avg * 0.4

    return {"bat": bat_power, "pit": pit_power}


# =========================================
# 단일 경기 시뮬레이션
# =========================================
def _simulate_game(home_power, away_power):
    home_exp = _expected_runs(home_power["bat"], away_power["pit"])
    away_exp = _expected_runs(away_power["bat"], home_power["pit"])
    
    home_exp *= 1.05 + home_power.get("home_adv", 0.0)

    home_score = _random_runs(home_exp)
    away_score = _random_runs(away_exp)

    if home_score == away_score and random.random() < 0.85:
        if random.random() < home_exp / (home_exp + away_exp):
            home_score += 1
        else:
            away_score += 1

    return home_score, away_score


def _expected_runs(bat, pit):
    diff = bat - pit
    base = 4.5 + diff * 0.09
    return max(1.2, min(9.0, base))


def _random_runs(expected):
    runs = 0
    remaining = expected
    while remaining > 0:
        if random.random() < min(remaining, 1.0) * 0.75:
            runs += 1
        remaining -= 1.0

    if random.random() < 0.12:
        runs += random.randint(1, 4)
    if random.random() < 0.05:
        runs = max(0, runs - random.randint(1, 2))

    return runs
