# dynasty_history.py
# =========================================
# KBO Dynasty - 시즌 역사 / 우승 기록
# 사전 준비 (Supabase SQL Editor):
#
# CREATE TABLE IF NOT EXISTS dynasty_history (
#     id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
#     save_id bigint,
#     season int,
#     team_id bigint,
#     team_name text,
#     logo text,
#     rank int,
#     wins int,
#     losses int,
#     ties int,
#     champion boolean DEFAULT false
# );
# =========================================

from dynasty_utils import get_supabase, get_standings


# =========================================
# 시즌 최종 순위 기록 (next_season 진입 시 호출)
# 성적 리셋 전에 호출해야 한다
# =========================================
def record_season_history(save_id):
    sb = get_supabase()
    save = (
        sb.table("dynasty_save")
        .select("season, ks_champion")
        .eq("id", save_id)
        .execute()
        .data[0]
    )
    season = save["season"]
    ks_champion = save.get("ks_champion")

    # 중복 기록 방지
    existing = (
        sb.table("dynasty_history")
        .select("id", count="exact")
        .eq("save_id", save_id)
        .eq("season", season)
        .execute()
        .count
    )
    if existing and existing > 0:
        return 0

    teams = (
        sb.table("dynasty_team")
        .select("*")
        .eq("save_id", save_id)
        .execute()
        .data
    )
    standings = get_standings(teams)

    rows = []
    for i, t in enumerate(standings):
        # 챔피언 = KS 우승팀 (포스트시즌 미진행 세이브는 정규 1위)
        is_champ = (t["id"] == ks_champion) if ks_champion else (i == 0)
        rows.append(
            {
                "save_id": save_id,
                "season": season,
                "team_id": t["id"],
                "team_name": t["team_name"],
                "logo": t["logo"],
                "rank": i + 1,
                "wins": t["wins"],
                "losses": t["losses"],
                "ties": t["ties"],
                "champion": is_champ,
            }
        )

    sb.table("dynasty_history").insert(rows).execute()

    # 우승 뉴스: KS 미진행(구버전 세이브)일 때만 여기서 기록
    # (KS 진행 시엔 dynasty_postseason이 이미 우승 뉴스를 남김 → 중복 방지)
    if not ks_champion:
        try:
            from dynasty_event import log_event
            champ = standings[0]
            log_event(save_id, season, 99, "champion", "🏆",
                      f"Season {season} 우승: {champ['team_name']} ({champ['wins']}승 {champ['losses']}패)")
        except Exception:
            pass

    print(f"[dynasty_history] season {season} 기록 완료 (KS우승={ks_champion})")
    return len(rows)

# =========================================
# 전체 역사 조회 (시즌별 그룹)
# return: [{season, champion, rows: [...]}, ...] 최신 시즌 먼저
# =========================================
def get_history(save_id):
    sb = get_supabase()

    rows = (
        sb.table("dynasty_history")
        .select("*")
        .eq("save_id", save_id)
        .order("season", desc=True)
        .order("rank")
        .execute()
        .data
    )

    seasons = {}
    order = []
    for r in rows:
        s = r["season"]
        if s not in seasons:
            seasons[s] = {"season": s, "champion": None, "rows": []}
            order.append(s)
        seasons[s]["rows"].append(r)
        if r["champion"]:
            seasons[s]["champion"] = r

    return [seasons[s] for s in order]


# =========================================
# 팀별 우승 횟수 집계
# return: [{team_name, logo, titles}, ...] 우승 많은 순
# =========================================
def get_title_counts(save_id):
    sb = get_supabase()

    rows = (
        sb.table("dynasty_history")
        .select("team_name, logo")
        .eq("save_id", save_id)
        .eq("champion", True)
        .execute()
        .data
    )

    counts = {}
    for r in rows:
        key = r["team_name"]
        if key not in counts:
            counts[key] = {"team_name": key, "logo": r["logo"], "titles": 0}
        counts[key]["titles"] += 1

    result = list(counts.values())
    result.sort(key=lambda x: -x["titles"])
    return result
